// Code generated by "stringer -type=CommandResult"; DO NOT EDIT

package message

import "fmt"

const _CommandResult_name = "CommandSyncAckCommandSyncFailCommandAsyncAckCommandAsyncFailCommandAsyncSuccessCommandError"

var _CommandResult_index = [...]uint8{0, 14, 29, 44, 60, 79, 91}

func (i CommandResult) String() string {
	if i >= CommandResult(len(_CommandResult_index)-1) {
		return fmt.Sprintf("CommandResult(%d)", i)
	}
	return _CommandResult_name[_CommandResult_index[i]:_CommandResult_index[i+1]]
}
