// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// CommandResult is used to signal the sending partner about the result
// of this command
type CommandResult int32

const (
	// CommandSyncAck is used to acknowledge receipt of the command and
	// successful execution
	CommandResult_SyncAck CommandResult = 1
	// CommandSyncFail is used to acknowledge receipt of the command and
	// unsuccessful execution
	CommandResult_SyncFail CommandResult = 2
	// CommandAsyncAck is used to acknowledge receipt of the command but
	// immediate result is not available. The caller should monitor the
	// command queue to wait for the async result
	CommandResult_AsyncAck CommandResult = 3
	// CommandAsyncFail is used to signal failure on an async command.
	// Message should be consulted to see the reason.
	CommandResult_AsyncFail CommandResult = 4
	// CommandAsyncSuccess is used to signal success on an async command
	CommandResult_AsyncSuccess CommandResult = 5
	// CommandError is used to signal a failure with executing the command.
	// Message should be consulted to see the reason.
	CommandResult_Error CommandResult = 6
)

var CommandResult_name = map[int32]string{
	1: "SyncAck",
	2: "SyncFail",
	3: "AsyncAck",
	4: "AsyncFail",
	5: "AsyncSuccess",
	6: "Error",
}
var CommandResult_value = map[string]int32{
	"SyncAck":      1,
	"SyncFail":     2,
	"AsyncAck":     3,
	"AsyncFail":    4,
	"AsyncSuccess": 5,
	"Error":        6,
}

func (x CommandResult) Enum() *CommandResult {
	p := new(CommandResult)
	*p = x
	return p
}
func (x CommandResult) String() string {
	return proto.EnumName(CommandResult_name, int32(x))
}
func (x *CommandResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandResult_value, data, "CommandResult")
	if err != nil {
		return err
	}
	*x = CommandResult(value)
	return nil
}
func (CommandResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

// Command is used to send a command to a device on the network.
// The destination is the device UUID
type Command struct {
	Header           *Header `protobuf:"bytes,1,req,name=Header,json=header" json:"Header,omitempty"`
	ID               *string `protobuf:"bytes,2,req,name=ID,json=iD" json:"ID,omitempty"`
	Destination      *string `protobuf:"bytes,3,req,name=Destination,json=destination" json:"Destination,omitempty"`
	Component        *string `protobuf:"bytes,4,req,name=Component,json=component" json:"Component,omitempty"`
	Op               *string `protobuf:"bytes,5,req,name=Op,json=op" json:"Op,omitempty"`
	Parameters       *string `protobuf:"bytes,6,opt,name=Parameters,json=parameters" json:"Parameters,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Command) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Command) GetID() string {
	if m != nil && m.ID != nil {
		return *m.ID
	}
	return ""
}

func (m *Command) GetDestination() string {
	if m != nil && m.Destination != nil {
		return *m.Destination
	}
	return ""
}

func (m *Command) GetComponent() string {
	if m != nil && m.Component != nil {
		return *m.Component
	}
	return ""
}

func (m *Command) GetOp() string {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ""
}

func (m *Command) GetParameters() string {
	if m != nil && m.Parameters != nil {
		return *m.Parameters
	}
	return ""
}

// CommandReply is sent in response to a Command.
// It contains the result of a command and an optional message
type CommandReply struct {
	Header           *Header        `protobuf:"bytes,1,req,name=Header,json=header" json:"Header,omitempty"`
	InReplyTo        *string        `protobuf:"bytes,2,req,name=InReplyTo,json=inReplyTo" json:"InReplyTo,omitempty"`
	Result           *CommandResult `protobuf:"varint,3,req,name=Result,json=result,enum=message.CommandResult" json:"Result,omitempty"`
	Message          *string        `protobuf:"bytes,4,opt,name=Message,json=message" json:"Message,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CommandReply) Reset()                    { *m = CommandReply{} }
func (m *CommandReply) String() string            { return proto.CompactTextString(m) }
func (*CommandReply) ProtoMessage()               {}
func (*CommandReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *CommandReply) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CommandReply) GetInReplyTo() string {
	if m != nil && m.InReplyTo != nil {
		return *m.InReplyTo
	}
	return ""
}

func (m *CommandReply) GetResult() CommandResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return CommandResult_SyncAck
}

func (m *CommandReply) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "message.Command")
	proto.RegisterType((*CommandReply)(nil), "message.CommandReply")
	proto.RegisterEnum("message.CommandResult", CommandResult_name, CommandResult_value)
}

func init() { proto.RegisterFile("command.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0x41, 0x4e, 0xf3, 0x30,
	0x10, 0x85, 0x95, 0xb4, 0x4d, 0x7e, 0x4f, 0xd2, 0xfe, 0xd1, 0x2c, 0x90, 0x85, 0x2a, 0x14, 0x75,
	0x43, 0xc5, 0x22, 0x8b, 0xde, 0xa0, 0x6a, 0x41, 0x74, 0x81, 0x40, 0x29, 0x17, 0xb0, 0x1c, 0x0b,
	0x22, 0x1a, 0xdb, 0xb2, 0xdd, 0x45, 0x4f, 0xc3, 0x1d, 0x38, 0x21, 0x8a, 0x9d, 0x16, 0xb1, 0x63,
	0x15, 0xbd, 0xf7, 0xcd, 0x9b, 0xbc, 0x31, 0x4c, 0xb9, 0xea, 0x3a, 0x26, 0x9b, 0x4a, 0x1b, 0xe5,
	0x14, 0xa6, 0x9d, 0xb0, 0x96, 0xbd, 0x89, 0xeb, 0xfc, 0x5d, 0xb0, 0x46, 0x98, 0x60, 0x2f, 0xbe,
	0x22, 0x48, 0x37, 0x61, 0x10, 0x6f, 0x21, 0x79, 0xf4, 0x8c, 0x46, 0x65, 0xbc, 0xcc, 0x56, 0xff,
	0xab, 0x21, 0x53, 0x05, 0xbb, 0x4e, 0x42, 0x14, 0x67, 0x10, 0xef, 0xb6, 0x34, 0x2e, 0xe3, 0x25,
	0xa9, 0xe3, 0x76, 0x8b, 0x25, 0x64, 0x5b, 0x61, 0x5d, 0x2b, 0x99, 0x6b, 0x95, 0xa4, 0x23, 0x0f,
	0xb2, 0xe6, 0xc7, 0xc2, 0x39, 0x90, 0x8d, 0xea, 0xb4, 0x92, 0x42, 0x3a, 0x3a, 0xf6, 0x9c, 0xf0,
	0xb3, 0xd1, 0xef, 0x7b, 0xd6, 0x74, 0x12, 0xf6, 0x29, 0x8d, 0x37, 0x00, 0x2f, 0xcc, 0xb0, 0x4e,
	0x38, 0x61, 0x2c, 0x4d, 0xca, 0x68, 0x49, 0x6a, 0xd0, 0x17, 0x67, 0xf1, 0x19, 0x41, 0x3e, 0x94,
	0xae, 0x85, 0x3e, 0x9c, 0xfe, 0xde, 0x7c, 0x0e, 0x64, 0x27, 0x7d, 0xe6, 0x55, 0x0d, 0x07, 0x90,
	0xf6, 0x6c, 0x60, 0x05, 0x49, 0x2d, 0xec, 0xf1, 0xe0, 0xfc, 0x09, 0xb3, 0xd5, 0xd5, 0x65, 0xcd,
	0xe5, 0x6f, 0x3d, 0xad, 0x13, 0xe3, 0xbf, 0x48, 0x21, 0x7d, 0x0a, 0x03, 0x74, 0xec, 0x4b, 0x9e,
	0x1f, 0xf9, 0xae, 0x81, 0xe9, 0xaf, 0x08, 0x66, 0x90, 0xee, 0x4f, 0x92, 0xaf, 0xf9, 0x47, 0x11,
	0x61, 0x0e, 0xff, 0x7a, 0xf1, 0xc0, 0xda, 0x43, 0x11, 0xf7, 0x6a, 0x6d, 0x07, 0x36, 0xc2, 0x29,
	0x10, 0xaf, 0x3c, 0x1c, 0x63, 0x01, 0xb9, 0x97, 0xfb, 0x23, 0xe7, 0xc2, 0xda, 0x62, 0x82, 0x04,
	0x26, 0xf7, 0xc6, 0x28, 0x53, 0x24, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x1f, 0x4e, 0x71,
	0xe3, 0x01, 0x00, 0x00,
}
