// Code generated by protoc-gen-go.
// source: command.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CommandResult int32

const (
	// CommandSyncAck is used to acknowledge receipt of the command and
	// successful execution
	CommandResult_SyncAck CommandResult = 1
	// CommandSyncFail is used to acknowledge receipt of the command and
	// unsuccessful execution
	CommandResult_SyncFail CommandResult = 2
	// CommandAsyncAck is used to acknowledge receipt of the command but
	// immediate result is not available. The caller should monitor the
	// command queue to wait for the async result
	CommandResult_AsyncAck CommandResult = 3
	// CommandAsyncFail is used to signal failure on an async command.
	// Message should be consulted to see the reason.
	CommandResult_AsyncFail CommandResult = 4
	// CommandAsyncSuccess is used to signal success on an async command
	CommandResult_AsyncSuccess CommandResult = 5
	// CommandError is used to signal a failure with executing the command.
	// Message should be consulted to see the reason.
	CommandResult_Error CommandResult = 6
)

var CommandResult_name = map[int32]string{
	1: "SyncAck",
	2: "SyncFail",
	3: "AsyncAck",
	4: "AsyncFail",
	5: "AsyncSuccess",
	6: "Error",
}
var CommandResult_value = map[string]int32{
	"SyncAck":      1,
	"SyncFail":     2,
	"AsyncAck":     3,
	"AsyncFail":    4,
	"AsyncSuccess": 5,
	"Error":        6,
}

func (x CommandResult) Enum() *CommandResult {
	p := new(CommandResult)
	*p = x
	return p
}
func (x CommandResult) String() string {
	return proto.EnumName(CommandResult_name, int32(x))
}
func (x *CommandResult) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CommandResult_value, data, "CommandResult")
	if err != nil {
		return err
	}
	*x = CommandResult(value)
	return nil
}
func (CommandResult) EnumDescriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type Command struct {
	Header           *Header `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	ID               []byte  `protobuf:"bytes,2,req,name=ID" json:"ID,omitempty"`
	Destination      []byte  `protobuf:"bytes,3,req,name=Destination" json:"Destination,omitempty"`
	Component        *string `protobuf:"bytes,4,req,name=Component" json:"Component,omitempty"`
	Op               *string `protobuf:"bytes,5,req,name=Op" json:"Op,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Command) Reset()                    { *m = Command{} }
func (m *Command) String() string            { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()               {}
func (*Command) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *Command) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Command) GetID() []byte {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *Command) GetDestination() []byte {
	if m != nil {
		return m.Destination
	}
	return nil
}

func (m *Command) GetComponent() string {
	if m != nil && m.Component != nil {
		return *m.Component
	}
	return ""
}

func (m *Command) GetOp() string {
	if m != nil && m.Op != nil {
		return *m.Op
	}
	return ""
}

type CommandReply struct {
	Header           *Header        `protobuf:"bytes,1,req,name=Header" json:"Header,omitempty"`
	InReplyTo        []byte         `protobuf:"bytes,2,req,name=InReplyTo" json:"InReplyTo,omitempty"`
	Result           *CommandResult `protobuf:"varint,3,req,name=Result,enum=message.CommandResult" json:"Result,omitempty"`
	Message          *string        `protobuf:"bytes,4,opt,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *CommandReply) Reset()                    { *m = CommandReply{} }
func (m *CommandReply) String() string            { return proto.CompactTextString(m) }
func (*CommandReply) ProtoMessage()               {}
func (*CommandReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *CommandReply) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *CommandReply) GetInReplyTo() []byte {
	if m != nil {
		return m.InReplyTo
	}
	return nil
}

func (m *CommandReply) GetResult() CommandResult {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return CommandResult_SyncAck
}

func (m *CommandReply) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Command)(nil), "message.Command")
	proto.RegisterType((*CommandReply)(nil), "message.CommandReply")
	proto.RegisterEnum("message.CommandResult", CommandResult_name, CommandResult_value)
}

func init() { proto.RegisterFile("command.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x8e, 0xb1, 0x6e, 0xb3, 0x30,
	0x14, 0x85, 0x85, 0x13, 0xe0, 0xf7, 0x05, 0xf2, 0xa3, 0x3b, 0x54, 0x56, 0x95, 0x01, 0x65, 0x29,
	0xea, 0xc0, 0x90, 0x37, 0x88, 0x42, 0xab, 0x32, 0x54, 0x91, 0x9c, 0xbe, 0x00, 0x02, 0xab, 0x45,
	0x05, 0x1b, 0x61, 0x32, 0xe4, 0x35, 0xfa, 0x02, 0x7d, 0xd5, 0x0a, 0xe3, 0x26, 0xed, 0xd6, 0xf1,
	0x7c, 0xdf, 0x3d, 0xf6, 0x81, 0xa8, 0x52, 0x5d, 0x57, 0xca, 0x3a, 0xeb, 0x07, 0x35, 0x2a, 0xf4,
	0x3b, 0xa1, 0x75, 0xf9, 0x2a, 0x6e, 0xc3, 0x37, 0x51, 0xd6, 0x62, 0x98, 0xf1, 0xe6, 0xc3, 0x01,
	0x7f, 0x3f, 0x1f, 0xe2, 0x1d, 0x78, 0x4f, 0xc6, 0x31, 0x27, 0x21, 0x69, 0xb0, 0xfd, 0x9f, 0xd9,
	0x4e, 0x36, 0x63, 0x6e, 0x35, 0xae, 0x80, 0x14, 0x39, 0x23, 0x09, 0x49, 0x43, 0x4e, 0x8a, 0x1c,
	0x13, 0x08, 0x72, 0xa1, 0xc7, 0x46, 0x96, 0x63, 0xa3, 0x24, 0x5b, 0x18, 0xf1, 0x13, 0xe1, 0x1a,
	0xe8, 0x5e, 0x75, 0xbd, 0x92, 0x42, 0x8e, 0x6c, 0x99, 0x90, 0x94, 0xf2, 0x2b, 0x98, 0xde, 0x3b,
	0xf4, 0xcc, 0x35, 0x98, 0x1c, 0xfa, 0xcd, 0xa7, 0x03, 0xa1, 0x1d, 0xc5, 0x45, 0xdf, 0x9e, 0xff,
	0xbe, 0x6c, 0x0d, 0xb4, 0x90, 0xa6, 0xf3, 0xa2, 0xec, 0xc0, 0x2b, 0xc0, 0x0c, 0x3c, 0x2e, 0xf4,
	0xa9, 0x1d, 0xcd, 0xc4, 0xd5, 0xf6, 0xe6, 0xf2, 0xcc, 0xe5, 0xb7, 0xc9, 0x72, 0x7b, 0x85, 0x0c,
	0xfc, 0xe7, 0xf9, 0x80, 0x2d, 0x13, 0x27, 0xa5, 0xfc, 0x3b, 0xde, 0xd7, 0x10, 0xfd, 0xaa, 0x60,
	0x00, 0xfe, 0xf1, 0x2c, 0xab, 0x5d, 0xf5, 0x1e, 0x3b, 0x18, 0xc2, 0xbf, 0x29, 0x3c, 0x96, 0x4d,
	0x1b, 0x93, 0x29, 0xed, 0xb4, 0x75, 0x0b, 0x8c, 0x80, 0x9a, 0x64, 0xe4, 0x12, 0x63, 0x08, 0x4d,
	0x3c, 0x9e, 0xaa, 0x4a, 0x68, 0x1d, 0xbb, 0x48, 0xc1, 0x7d, 0x18, 0x06, 0x35, 0xc4, 0xde, 0x57,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x47, 0x18, 0xb7, 0x67, 0xc3, 0x01, 0x00, 0x00,
}
