// Code generated by protoc-gen-go.
// source: discover.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Discover is a message used by the inventory to discover
// all available devices in the network.
// Drivers should respond with a Register message directed to the source
type Discover struct {
	Header           *Header `protobuf:"bytes,1,req,name=Header,json=header" json:"Header,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Discover) Reset()                    { *m = Discover{} }
func (m *Discover) String() string            { return proto.CompactTextString(m) }
func (*Discover) ProtoMessage()               {}
func (*Discover) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *Discover) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*Discover)(nil), "message.Discover")
}

func init() { proto.RegisterFile("discover.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 89 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0xc9, 0x2c, 0x4e,
	0xce, 0x2f, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x95, 0xe2, 0xc9, 0x48, 0x4d, 0x4c, 0x81, 0x09, 0x2b, 0x19, 0x73, 0x71, 0xb8,
	0x40, 0x15, 0x0a, 0xa9, 0x73, 0xb1, 0x79, 0x80, 0xe5, 0x24, 0x18, 0x15, 0x98, 0x34, 0xb8, 0x8d,
	0xf8, 0xf5, 0xa0, 0x7a, 0xf4, 0x20, 0xc2, 0x41, 0x6c, 0x10, 0xad, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x6f, 0x20, 0x61, 0x96, 0x5c, 0x00, 0x00, 0x00,
}
