// Code generated by protoc-gen-go.
// source: register.proto
// DO NOT EDIT!

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Register will register the supplied Devices with the inventory.
// It is used by drivers to let the system know about devices.
// It is broadcasted at driver startup and unicasted to any
// device requesting the information using a Discovery message.
type Register struct {
	Header           *Header   `protobuf:"bytes,1,req,name=Header,json=header" json:"Header,omitempty"`
	Name             *string   `protobuf:"bytes,2,req,name=Name,json=name" json:"Name,omitempty"`
	Devices          []*Device `protobuf:"bytes,3,rep,name=Devices,json=devices" json:"Devices,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Register) Reset()                    { *m = Register{} }
func (m *Register) String() string            { return proto.CompactTextString(m) }
func (*Register) ProtoMessage()               {}
func (*Register) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{0} }

func (m *Register) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Register) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Register) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

// Unregister will unregister the supplied Devices from the inventory.
// It is used by drivers to let the system know devices have disappeared.
// It is also send at shutdown of a driver.
type Unregister struct {
	Header           *Header   `protobuf:"bytes,1,req,name=Header,json=header" json:"Header,omitempty"`
	Name             *string   `protobuf:"bytes,2,req,name=Name,json=name" json:"Name,omitempty"`
	Devices          []*Device `protobuf:"bytes,3,rep,name=Devices,json=devices" json:"Devices,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Unregister) Reset()                    { *m = Unregister{} }
func (m *Unregister) String() string            { return proto.CompactTextString(m) }
func (*Unregister) ProtoMessage()               {}
func (*Unregister) Descriptor() ([]byte, []int) { return fileDescriptor5, []int{1} }

func (m *Unregister) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Unregister) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Unregister) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

func init() {
	proto.RegisterType((*Register)(nil), "message.Register")
	proto.RegisterType((*Unregister)(nil), "message.Unregister")
}

func init() { proto.RegisterFile("register.proto", fileDescriptor5) }

var fileDescriptor5 = []byte{
	// 150 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x4a, 0x4d, 0xcf,
	0x2c, 0x2e, 0x49, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcf, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x95, 0xe2, 0xc9, 0x48, 0x4d, 0x4c, 0x81, 0x09, 0x4b, 0xf1, 0xa4, 0xa4, 0x96,
	0x65, 0x26, 0xa7, 0x42, 0x78, 0x4a, 0x45, 0x5c, 0x1c, 0x41, 0x50, 0x6d, 0x42, 0xea, 0x5c, 0x6c,
	0x1e, 0x60, 0x95, 0x12, 0x8c, 0x0a, 0x4c, 0x1a, 0xdc, 0x46, 0xfc, 0x7a, 0x50, 0x13, 0xf4, 0x20,
	0xc2, 0x41, 0x6c, 0x10, 0x83, 0x84, 0x84, 0xb8, 0x58, 0xfc, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14,
	0x98, 0x34, 0x38, 0x83, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x85, 0x34, 0xb9, 0xd8, 0x5d, 0xc0, 0x06,
	0x17, 0x4b, 0x30, 0x2b, 0x30, 0xa3, 0xe8, 0x86, 0x88, 0x07, 0xb1, 0x43, 0x2c, 0x2e, 0x56, 0x2a,
	0xe1, 0xe2, 0x0a, 0xcd, 0x2b, 0xa2, 0xb3, 0xad, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x45, 0xdf,
	0x8c, 0x34, 0x1f, 0x01, 0x00, 0x00,
}
