// Code generated by "stringer -type=Type"; DO NOT EDIT

package message

import "fmt"

const _Type_name = "TypeDiscoverTypeRegisterTypeUnregisterTypeInventoryTypeInventoryReplyTypeCommandTypeCommandReplyTypeEvent"

var _Type_index = [...]uint8{0, 12, 24, 38, 51, 69, 80, 96, 105}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return fmt.Sprintf("Type(%d)", i)
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
